# Default values for zipkin.
ui:
  replicaCount: 3
  maxReplicaCount: 5
  imageVersion: latest
  probeStartupDelay: 200
  targetCPUUtilizationPercentage: 80
  queryPort: 9411
  resources:
    ramMb: 2100
    javaOptsHeap: 1000
    cpuRequest: 80m
    cpuLimit: 300m
    spanLimit: 50000

configmap:
  name: zipkin-storage
  contactPoints:
    name: zipkin-storage
    key: cassandra.contactpoints
  username:
    name: zipkin-storage
    key: cassandra.username
  localdc:
    name: zipkin-storage
    key: cassandra.localdc

ingress:
  class: "nginx"
  path: /
  serviceName: zipkin-ui
  servicePort: 9411

storageMethod: mem

node:
  cpus: 2


