# Default values for zipkin.
collector:
  replicaCount: 3
  maxReplicaCount: 5
  targetCPUUtilizationPercentage: 80
  imageVersion: 2
  sampleRate: 0.1
  probeStartupDelay: 200
  queryPort: 9411
  resources:
    ramMb: 2100
    javaOptsHeap: 1000
    cpuRequest: 80m
    cpuLimit: 300m

ui:
  replicaCount: 1
  imageVersion: 2
  probeStartupDelay: 200
  queryPort: 9411
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 150m
    cpuLimit: 600m

configmap:
  name: zipkin-storage

ingress:
  class: "nginx"
  path: /
  serviceName: zipkin-ui
  servicePort: 9411

storageMethod: mem

node:
  cpus: 2


