apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: zipkin-collector
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zipkin-collector
  minReplicas: {{ .Values.ui.replicaCount }}
  maxReplicas: {{ .Values.ui.maxReplicaCount }}
  targetCPUUtilizationPercentage: {{ .Values.ui.targetCPUUtilizationPercentage }}
